spring.application.name=UserService

# DataSource Settings
spring.datasource.url=jdbc:mysql://localhost:3306/UserCatlogService
spring.datasource.username=root
spring.datasource.password=root12345
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


